### ISSUE TITLE
Tarefas

### ISSUE THREAD

**Issue by raphaelkieling** [raphaelkieling/PodNews#1]
# Todo

- [x] Geral
    - [ ] Criar CLI
    - [ ] Tornar mais fácil a configuração para pessoas que iriam utilizar
    - [ ] Parte gráfica (web)
    - [x] Decidir o limite de noticia que serão procurada
- [x] RobotNews
    - [x] Possibilidade de procurar notícias por uma pesquisa específica
    - [x] Conseguir selecionar as notícias encontradas
    - [x] Pegar notícias pelo google news
    - [x] Dar possibilidade de selecionar no terminal entre outros idiomas
    - [x] Dar possibilidade de selecionar no terminal entre categorias de notícias (tem na doc do google news)
    - [x] Separar sentenças
- [x] RobotCrawler
    - [x] Pegar notícias de outros sites através de um crawler
- [x] RobotFileManager
    - [x] Limpar pasta temporária
    - [x] Criar pasta temporária
    - [x] Responsavel pelo caminho da `/temp`
- [ ] RobotTextToSpeech
    - [x] Transformar texto em audio por sentença da notícia
    - [ ] Adicionar mais hosts
    - [x] Modificar idioma dos hosts automaticamente dependendo do idioma das notícias
- [ ] RobotAudio
    - [ ] Criar introdução automaticamente
    - [ ] Criar transições para ficar mais agradavel e organizado
    - [x] Concatenar audio das notícias
    - [x] Salvar uma transcrição
    - [ ] Organizar por pastas cada audio criado 
- [ ] RobotImage
    - [x] Conectar no google images
    - [x] Procurar imagem por search
    - [ ] Adicionar texto na imagem
    - [ ] Deixar fundo mais escuro para o texto aparecer bem
    - [x] Criar capa do PodNews
- [ ] RobotShare
    - [ ] Compartilhar no twitter
    - [ ] Compartilhar no facebook
    - [ ] Compartilhar no soundclound
    - [ ] Link para baixar
    - [ ] QR Code para baixar
    - [ ] Criar um podcast automaticamente em certo horário do dia e compartilhar

**Comment by operfildoluiz** [comment]
@raphaelkieling recomendo publicar no Anchor que é ilimtado e distribui pra outros agregadores.

O SoundCloud é muito limitado e não é uma boa solução pra podcasts

**Comment by raphaelkieling** [comment]
@lhcgoncalves eu tinha dado uma olhada nesse anchor quando vi no teu projeto, ele tem alguma API que facilite essa distribuição? Seria foda!

**Comment by operfildoluiz** [comment]
Não :/

Aí penso em usar o pupeteer pra interagir na Dashboard

**Comment by raphaelkieling** [comment]
Putz... logo que eu chegar em casa vou ver antes se existe uma forma de fazer isto via post, talvez alguma rota que ele envie pelo site a gente consiga se aproveitar

**Comment by raphaelkieling** [comment]
Mas em ultimo caso o pupe é parece totalmente viavel, só é um baita workaround pra fazer um processo que deveria ser simples se tivesse uma api kkk

**Comment by raphaelkieling** [comment]
@lhcgoncalves não consegui nada nem com o pupe nem no site, enviei um email para o pessoal do anchor. Atualizo aqui caso liberem alguma coisa

**Comment by operfildoluiz** [comment]
Por pupeteer não rolou aqui tbm :/
